SimpleForum/Models/Search/SearchResultModel.cs
using SimpleForum.Models.Post;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Search
{
    public class SearchResultModel
    {
        public IEnumerable<PostListingModel> Posts { get; set; }
        public string SearchQuery { get; set; }
        public bool EmptySearchResults { get; set; }
    }
}

SimpleForum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimpleForum.CustomAttribute;
using SimpleForum.Data;
using SimpleForum.Data.Models;
using SimpleForum.Helper;
using SimpleForum.Models.Forum;
using SimpleForum.Models.Post;
using X.PagedList;

namespace SimpleForum.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum forumService;
        private readonly IPost postService;
        private readonly int pageSize = 10;

        public ForumController(IForum forum, IPost post)
        {
            forumService = forum;
            postService = post;
        }

        [Throttle(Name = "ThrottleTest", Seconds = 5)]
        [OutputCache(Profile = "default")]
        public IActionResult Index()
        {
            var forums = forumService.GetAll()
                .Select(f => new ForumListingModel
                {
                    Id = f.ID,
                    Description = f.Description,
                    Name = f.Title,
                    ImageUrl=f.ImageUrl,
                    LatestPost=postService.GetLatestPostByForumID(f.ID)
                });



            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        [Route("Forum/{id}/{pageNumber?}/{searchQuery?}")]
        [OutputCache(Profile = "default")]
        public IActionResult Topic(int id, int? pageNumber = 1, string searchQuery="")
        {
            var forum = forumService.GetByID(id);

            var post = postService.GetFilteredPost(forum, searchQuery).ToList();
            

            var postListing = post.Select(p => new PostListingModel
            {
                Id = p.ID,
                AuthorName=p.User.UserName,
                AuthorId = p.User.Id,
                AuthorRating = p.User.Rating,
                Title = p.Title,
                DatePosted = p.Created.ToString(),
                RepliesCount=p.Replies.Count(),
                Slug=p.Slug,
                Forum= BuildForumListing(p)
            });

            var model = new ForumTopicModel
            {
                Forum = BuildForumListing(forum)
            };

            var pageN = pageNumber ?? 1;
            var onePageOfPost = postListing.ToPagedList(pageN, pageSize);
            ViewBag.OnePageOfPost = onePageOfPost;
            return View(model);
        }

        [HttpPost]
        public IActionResult Search(int id, string searchQuery)
        {
            return RedirectToAction("Topic", new { id,pageNumber=1, searchQuery });
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.ID,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }

        private ForumListingModel BuildForumListing(Post p)
        {
            var forum = p.Forum;
            return BuildForumListing(forum);
        }
    }
}

SimpleForum/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimpleForum.CustomAttribute;
using SimpleForum.Data;
using SimpleForum.Data.Models;
using SimpleForum.Models.Forum;
using SimpleForum.Models.Post;
using SimpleForum.Models.Search;
using X.PagedList;

namespace SimpleForum.Controllers
{
    public class SearchController : Controller
    {
        private readonly IPost postService;
        private readonly int pageSize = 10;

        public SearchController(IPost post)
        {
            postService = post;
        }

        [HttpPost]
        public IActionResult Search(string searchQuery)
        {
            return RedirectToAction("Results", new { searchQuery });
        }

        [Route("{controller}/{action}/{searchQuery}/{pageNumber?}")]
        [Throttle(Name = "ThrottleTest", Seconds = 5)]
        [OutputCache(Profile = "default")]
        public IActionResult Results(string searchQuery, int? pageNumber)
        {
            var post = postService.GetFilteredPost(searchQuery);

            var areNoResults = (!string.IsNullOrEmpty(searchQuery)) && !post.Any();

            var postListing = post.Select(p => new PostListingModel
            {
                Id=p.ID,
                AuthorName=p.User.UserName,
                AuthorId=p.User.Id,
                AuthorRating=p.User.Rating,
                Title=p.Title,
                Slug=p.Slug,
                DatePosted=p.Created.ToString(),
                RepliesCount=p.Replies.Count(),
                Forum= BuildForumListing(p)
            });

            var model = new SearchResultModel
            {
                SearchQuery=searchQuery,
                EmptySearchResults=areNoResults
            };
            var pageN = pageNumber ?? 1;
            var onePageOfPost = postListing.ToPagedList(pageN, pageSize);
            ViewBag.OnePageOfPost = onePageOfPost;

            return View(model);
        }

        private ForumListingModel BuildForumListing(Post p)
        {
            var forum = p.Forum;

            return new ForumListingModel
            {
                Id = forum.ID,
                ImageUrl = forum.ImageUrl,
                Description = forum.Description,
                Name = forum.Title
            };
        }
    }
}

SimpleForum/Views/Search/Results.cshtml
@model SimpleForum.Models.Search.SearchResultModel
@using SimpleForum.Models.Post
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@{ 
    ViewData["Title"] = "Kết quả tìm kiếm cho: " +@Model.SearchQuery;
}

<div class="container body-content">
    <div class="row sectionHeader">
        <div class="sectionHeading">
            <span id="results">Kết quả tìm kiếm cho: @Model.SearchQuery</span>
            <form asp-controller="Search" asp-action="Search" method="post">
                <div class="searchForm">
                    <input asp-for="SearchQuery" type="text" placeholder="Tìm kiếm..." class="searchBar" onfocus="clearThis(this)">
                    <button type="submit" class="btn buttonSearch">
                        <i class="material-icons">search</i>
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="row" id="forumIndexContent">
        @if (((IEnumerable<PostListingModel>)ViewBag.OnePageOfPost).Any())
        {
            <table class="table table-hover table-bordered" id="forumIndexTable">
                <tbody>
                    @foreach (var post in ViewBag.OnePageOfPost)
                    {
                        <tr>
                            <td>
                                <div class="forumLogo" style="background-image: url(@post.Forum.ImageUrl); background-size:100%"></div>
                                <div class="postData">
                                    <div class="postTitle">
                                        <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Slug">@post.Title</a>
                                    </div>
                                    <div class="forumSubTitle">
                                        <div>
                                            bởi:
                                            <span class="postAuthor">
                                                <a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.AuthorId">
                                                    @post.AuthorName
                                                </a>
                                            </span>
                                            ở:
                                            <span class="postForum">
                                                <a asp-controller="Forum" asp-action="Topic" asp-route-id="@post.Forum.Id">@post.Forum.Name</a>
                                            </span>
                                            lúc:
                                            <span class="postDate">
                                                @post.DatePosted
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <div class="forumPostCount">
                                    Trả lời: @post.RepliesCount
                                </div>
                            </td>
                            <td>
                                <div class="postDate">@post.DatePosted</div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            @Html.PagedListPager((IPagedList)ViewBag.OnePageOfPost, pageNumber => Url.Action("Results", "Search", new { searchQuery=Model.SearchQuery, pageNumber = pageNumber}))
        }
        else if (@Model.EmptySearchResults)
        {
            <div class="noPosts">
                <i class="material-icons md-72">question_answer</i>
                <h3>
                    Không tìm thấy kết quả nào của @Model.SearchQuery! <br />
                </h3>
            </div>

        }
    </div>
</div>

@section Scripts {
    <script>
        function clearThis(target) {
            target.value = "";
        }
    </script>
}