SimpleForum/Areas/Admin/Models/Review/ReviewPostListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Areas.Admin.Models.Review
{
    public class ReviewPostListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Slug { get; set; }
        public DateTime Created { get; set; }
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string UserImgUrl { get; set; }
    }
}

SimpleForum/Areas/Admin/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SimpleForum.Areas.Admin.Models.Review;
using SimpleForum.Data;

namespace SimpleForum.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ReviewController : Controller
    {
        private readonly IPost _post;

        public ReviewController(IPost post)
        {
            _post = post;
        }

        public IActionResult Index()
        {
            var postNeedToReview = _post.GetAllNeedReviewPost();

            var model = postNeedToReview.Select(p => new ReviewPostListingModel
            {
                Id = p.ID,
                Title = p.Title,
                UserId = p.User.Id,
                UserName = p.User.UserName,
                UserImgUrl = p.User.ProfileImageUrl,
                Created = p.Created,
                Slug=p.Slug
            });

            ViewBag.NumberOfPostNeedReview = (int?)postNeedToReview.Count() ?? 0;
            return View(model);
        }
              
        public async Task<IActionResult> Accept(string id)
        {
            var post = _post.GetBySlug(id);
            await _post.AcceptPost(id);
            return RedirectToAction("Index");
        }
    }
}

SimpleForum/Areas/Admin/Views/Review/Index.cshtml
@model IEnumerable<SimpleForum.Areas.Admin.Models.Review.ReviewPostListingModel>


@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Phê duyệt các bài viết";
}

<div class="row" id="forumIndexContent">
    <h1>Phê duyệt các bài viết</h1>
    @if (Model.Any())
    {
        <table class="table table-striped table-responsive-md btn-table">

            <thead>
                <tr>
                    <th>Tiêu đề</th>
                    <th>Tên thành viên</th>
                    <th>Thời gian</th>
                    <th>Hành động</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var post in Model)
                {
                    <tr>
                        <td>
                            <a asp-controller="Post" asp-action="Index" asp-route-id="@post.Slug">@post.Title</a>
                        </td>
                        <td><a asp-controller="Profile" asp-action="Detail" asp-route-id="@post.UserId">@post.UserName</a></td>
                        <td>
                            <span class="postDate">@post.Created</span>
                        </td>
                        <td>
                            <p><a class="btn btn-info" asp-area="Admin" asp-controller="Review" asp-action="Accept" asp-route-id="@post.Slug">Duyệt bài</a></p>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    }
    else
    {
        <div class="noPosts">
            <h3>
                Hiện không có bài viết nào cần phê duyệt!
            </h3>
        </div>

    }
</div>