SimpleForum/Models/Post/DeletePostModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Post
{
    public class DeletePostModel
    {
        public string PostId { get; set; }
        public int ForumId { get; set; }
        public string PostAuthor { get; set; }
        public string PostContent { get; set; }
        public bool IsActive { get; set; }
    }
}

SimpleForum/Models/Post/EditPostModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Post
{
    public class EditPostModel
    {
        [Required(ErrorMessage = "Nội dung tiêu đề phải có!")]
        [StringLength(200, ErrorMessage = "{0} phải có ít nhất {2} kí tự và tối đa {1} kí tự.", MinimumLength = 3)]
        [Display(Name = "Tiêu đề")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Nội dung bài viết phải có!")]
        [StringLength(50000, ErrorMessage = "{0} phải có ít nhất {2} kí tự và tối đa {1} kí tự.", MinimumLength = 10)]
        [Display(Name = "Nội dung")]
        public string Content { get; set; }

        public string PostID { get; set; }
        public bool IsActive { get; set; }
    }
}

SimpleForum/Models/Post/MovePostIndexModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Post
{
    public class MovePostIndexModel
    {
        public string PostId { get; set; }
        public int NewForumId { get; set; }
        public int OldForumId { get; set; }
        public IEnumerable<Data.Models.Forum> Forums { get; set; }

    }
}

SimpleForum/Models/Post/NewPostModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Post
{
    public class NewPostModel
    {
        public string ForumName { get; set; }
        public int ForumId{ get; set; }
        public string AuthorName { get; set; }
        public bool IsActive{ get; set; }
        public string UserName { get; set; }
        public string ForumImageUrl { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = "{0} phải có ít nhất {2} kí tự và tối đa {1} kí tự.", MinimumLength = 3)]
        [Display(Name = "Tiêu đề")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Nội dung bài viết phải có!")]
        [StringLength(50000, ErrorMessage = "{0} phải có ít nhất {2} kí tự và tối đa {1} kí tự.", MinimumLength = 10)]
        [Display(Name = "Nội dung")]
        public string Content { get; set; }

        public DateTime Created { get; set; }
    }
}

SimpleForum/Models/Post/PostIndexModel.cs
using SimpleForum.Models.Reply;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Post
{
    public class PostIndexModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string AuthorName { get; set; }
        public string AuthorID { get; set; }
        public bool IsActive { get; set; }
        public string AuthorImageUrl { get; set; }
        public DateTime Created { get; set; }
        public string PostContent { get; set; }
        public int ForumId { get; set; }
        public string ForumName { get; set; }
        public bool IsAuthorAdmin { get; set; }
        public bool IsMod { get; set; }
        public bool CloseOrOpen { get; set; }
        public bool IsReview { get; set; }
        public string Slug { get; set; }

        public IEnumerable<PostReplyModel> Replies { get; set; }
    }
}

SimpleForum/Models/Post/PostListingModel.cs
using SimpleForum.Models.Forum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Models.Post
{
    public class PostListingModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string AuthorName { get; set; }
        public int AuthorRating { get; set; }
        public string AuthorId { get; set; }
        public string DatePosted { get; set; }
        public string Slug { get; set; }

        //public int ForumID { get; set; }
        //public string ForumImageUrl { get; set; }
        //public string ForumName { get; set; }
        public ForumListingModel Forum { get; set; }
        public int RepliesCount { get; set; }
    }
}

SimpleForum/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SimpleForum.CustomAttribute;
using SimpleForum.Data;
using SimpleForum.Data.Models;
using SimpleForum.Helper;
using SimpleForum.Models.Forum;
using SimpleForum.Models.Post;
using X.PagedList;

namespace SimpleForum.Controllers
{
    public class ForumController : Controller
    {
        private readonly IForum forumService;
        private readonly IPost postService;
        private readonly int pageSize = 10;

        public ForumController(IForum forum, IPost post)
        {
            forumService = forum;
            postService = post;
        }

        [Throttle(Name = "ThrottleTest", Seconds = 5)]
        [OutputCache(Profile = "default")]
        public IActionResult Index()
        {
            var forums = forumService.GetAll()
                .Select(f => new ForumListingModel
                {
                    Id = f.ID,
                    Description = f.Description,
                    Name = f.Title,
                    ImageUrl=f.ImageUrl,
                    LatestPost=postService.GetLatestPostByForumID(f.ID)
                });



            var model = new ForumIndexModel
            {
                ForumList = forums
            };

            return View(model);
        }

        [Route("Forum/{id}/{pageNumber?}/{searchQuery?}")]
        [OutputCache(Profile = "default")]
        public IActionResult Topic(int id, int? pageNumber = 1, string searchQuery="")
        {
            var forum = forumService.GetByID(id);

            var post = postService.GetFilteredPost(forum, searchQuery).ToList();
            

            var postListing = post.Select(p => new PostListingModel
            {
                Id = p.ID,
                AuthorName=p.User.UserName,
                AuthorId = p.User.Id,
                AuthorRating = p.User.Rating,
                Title = p.Title,
                DatePosted = p.Created.ToString(),
                RepliesCount=p.Replies.Count(),
                Slug=p.Slug,
                Forum= BuildForumListing(p)
            });

            var model = new ForumTopicModel
            {
                Forum = BuildForumListing(forum)
            };

            var pageN = pageNumber ?? 1;
            var onePageOfPost = postListing.ToPagedList(pageN, pageSize);
            ViewBag.OnePageOfPost = onePageOfPost;
            return View(model);
        }

        [HttpPost]
        public IActionResult Search(int id, string searchQuery)
        {
            return RedirectToAction("Topic", new { id,pageNumber=1, searchQuery });
        }

        private ForumListingModel BuildForumListing(Forum forum)
        {
            return new ForumListingModel
            {
                Id = forum.ID,
                Name = forum.Title,
                Description = forum.Description,
                ImageUrl = forum.ImageUrl
            };
        }

        private ForumListingModel BuildForumListing(Post p)
        {
            var forum = p.Forum;
            return BuildForumListing(forum);
        }
    }
}

SimpleForum/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.SignalR;
using SimpleForum.CustomAttribute;
using SimpleForum.Data;
using SimpleForum.Data.Models;
using SimpleForum.Helper;
using SimpleForum.Helper.Recapcha;
using SimpleForum.Hubs;
using SimpleForum.Models.Reply;

namespace SimpleForum.Controllers
{
    public class ReplyController : Controller
    {
        private readonly IForum _forumService;
        private readonly IPost _postService;
        private readonly IPostReply _postReply;
        private readonly IApplicationUser _userService;
        private readonly IPostFormatter postFormatter;
        private readonly IHubContext<NotiHub> _hubContext;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RecaptchaSettings _recapchaSettings;
        private readonly int pageSize=10;
        private readonly LinkGenerator _linkGenerator;

        public ReplyController(IForum forumService, IPost postService, IApplicationUser userService, IPostReply reply, UserManager<ApplicationUser> userManager, IPostFormatter formatter, IHubContext<NotiHub> hubContext, RecaptchaSettings recapchaSettings, LinkGenerator linkGenerator)
        {
            _forumService = forumService;
            _postService = postService;
            _userService = userService;
            _postReply = reply;
            _userManager = userManager;
            postFormatter = formatter;
            _hubContext = hubContext;
            _recapchaSettings = recapchaSettings;
            _linkGenerator = linkGenerator;
        }

        [Throttle(Name = "ThrottleTest", Seconds = 5)]
        public async Task<IActionResult> Create(string id)
        {
            var post = _postService.GetBySlug(id);
            var forum = _forumService.GetByID(post.Forum.ID);

            var name = User.Identity.Name;

            var user = await _userManager.FindByNameAsync(name);

            var model = new PostReplyModel
            {
                PostContent = postFormatter.Prettify(post.Content),
                PostTitle = post.Title,
                PostId = post.ID,
                CloseOrOpen=post.CloseOrOpen,
                ForumName = forum.Title,
                ForumId = forum.ID,
                ForumImageUrl = forum.ImageUrl,
                Slug=post.Slug,
                AuthorName = User.Identity.Name,
                AuthorImageUrl = user.ProfileImageUrl,
                AuthorId = user.Id,
                AuthorRating = user.Rating,
                IsAdmin = IsAuthorAdmin(user),
                IsMod=IsAuthorMod(user),
                IsActive=user.IsActive,
                IsReview=post.IsReview,
                Date = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time")),
                //Date = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Asia/Ho_Chi_Minh")),
                NumberOfReply =post.Replies.Count()
            };

            return View(model);
        }

        private bool IsAuthorAdmin(ApplicationUser user)
        {
            var role = _userManager.GetRolesAsync(user).Result;
            return role.Contains("Admin");
        }
        private bool IsAuthorMod(ApplicationUser user)
        {
            var role = _userManager.GetRolesAsync(user).Result;
            return role.Contains("Mod");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddReply(PostReplyModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var user = await _userManager.FindByIdAsync(userId);
                if( !IsAuthorAdmin(user) && !IsAuthorMod(user) && _postService.GetPostCountUser(user.Id) < 6)
                {
                    if (!await RecaptchaHelper.IsReCaptchaPassedAsync(Request.Form["g-recaptcha-response"], _recapchaSettings.SecretKey))
                    {
                        ModelState.AddModelError(string.Empty, "Recaptcha nói rằng bạn không phải là người!");
                        return RedirectToAction("Create", new { id = model.Slug });
                    }

                }
                var reply = BuildReply(model, user);
                await _postService.AddReply(reply);                
                var pageNumber = Math.Ceiling((double)(model.NumberOfReply+1) / pageSize);
                if (pageNumber == 0) pageNumber = 1;

                var count = (model.NumberOfReply+1) % pageSize;
                if (count == 0) count = 10;

                var htmlData = CreateHtmlReply(reply, count);

                await _hubContext.Clients.All.SendAsync("ReceiveNotify", model.Slug, (model.NumberOfReply + 1) % pageSize, pageNumber, htmlData);

                var link = _linkGenerator.GetPathByAction("Index", "Post", new { id = model.Slug, pageNumber = pageNumber }, new PathString(), new FragmentString($"#{count}"), new LinkOptions());
                return Redirect(link);
                //return RedirectToAction("Index", "Post", new { id = model.Slug, pageNumber = pageNumber }, fragment:$"{count}");
            }
            else return RedirectToAction("Create", new { id = model.Slug });
        }

        public string CreateHtmlReply(PostReply model, int count)
        {
            var linkProfile = _linkGenerator.GetPathByAction("Detail", "Profile", new { id = model.User.Id });
            string data = string.Empty;
            
            if(IsAuthorAdmin(model.User) && model.User.IsActive)
            {
                 data = $"<div class=\"row replyContent\" id=\"{count}\">\r\n " +
                    $"<div class=\"col-md-3 replyAuthorContainer\">\r\n " +
                    $"<div class=\"postAuthorImage\" style=\"background-image: url({model.User.ProfileImageUrl})\"></div><br/>\r\n" +
                    $"<a href=\"{linkProfile}\">{model.User.UserName}</a><br />" +
                    $"<span style=\"color: red\">Admin</span><br />" +
                    $"<span>{model.Created}</span>" + $"</div>\r\n" +
                    $"<div class=\"col-md-9 replyContentContainer\">\r\n" +
                    $"<div class=\"postContent\">\r\n" +
                    $"{model.Content}" +
                    $"</div>\r\n" + $"</div>\r\n" +
                    $"</div>";
                return data;
            }
            if(IsAuthorMod(model.User) && model.User.IsActive)
            {
                data = $"<div class=\"row replyContent\" id=\"{count}\">\r\n " +
                   $"<div class=\"col-md-3 replyAuthorContainer\">\r\n " +
                   $"<div class=\"postAuthorImage\" style=\"background-image: url({model.User.ProfileImageUrl})\"></div><br/>\r\n" +
                   $"<a href=\"{linkProfile}\">{model.User.UserName}</a><br />" +
                   $"<span style=\"color: hotpink\">Mod</span><br />" +
                   $"<span>{model.Created}</span>" + $"</div>\r\n" +
                   $"<div class=\"col-md-9 replyContentContainer\">\r\n" +
                   $"<div class=\"postContent\">\r\n" +
                   $"{model.Content}" +
                   $"</div>\r\n" + $"</div>\r\n" +
                   $"</div>";
                return data;
            }
            if (model.User.IsActive)
            {
                data = $"<div class=\"row replyContent\" id=\"{count}\">\r\n " +
                    $"<div class=\"col-md-3 replyAuthorContainer\">\r\n " +
                    $"<div class=\"postAuthorImage\" style=\"background-image: url({model.User.ProfileImageUrl})\"></div><br/>\r\n" +
                    $"<a href=\"{linkProfile}\">{model.User.UserName}</a><br />" +
                    $"<span>{model.Created}</span>" + $"</div>\r\n" +
                    $"<div class=\"col-md-9 replyContentContainer\">\r\n" +
                    $"<div class=\"postContent\">\r\n" +
                    $"{model.Content}" +
                    $"</div>\r\n" + $"</div>\r\n" +
                    $"</div>";
                return data;
            }

            return data;
        }

        private PostReply BuildReply(PostReplyModel reply, ApplicationUser user)
        {
            var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("SE Asia Standard Time"));
            //var now = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Asia/Ho_Chi_Minh"));
            var post = _postService.GetByID(reply.PostId);

            return new PostReply
            {
                Post = post,
                Content = reply.ReplyContent,
                Created = now,
                User = user
            };
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = _userManager.GetUserId(User);
            var user = await _userManager.FindByIdAsync(userId);
            var reply = _postReply.GetById(id);

            var model = new DeleteReplyModel
            {
                PostID=reply.Post.ID,
                ReplyId=id,
                IsActive = user.IsActive
            };

            if (userId == reply.User?.Id || User.IsInRole("Admin") || User.IsInRole("Mod"))
                return View(model);
            else
                return RedirectToAction("Index", "Post", new { id = reply.Post.Slug });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteReply(int ReplyId)
        {
            var reply = _postReply.GetById(ReplyId);
            await _postReply.Delete(ReplyId);

SimpleForum/Views/Post/Create.cshtml
@model SimpleForum.Models.Post.NewPostModel
@{
    var host = Context.Request.Host.ToString();
    ViewData["Title"] = "Tạo bài viết mới";
}

@if (Model.IsActive)
{
    <div class="createPostSection">
        <h1>Bài viết mới | @Model.ForumName</h1>

        <form asp-action="AddPost" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title">Tiêu đề</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content">Nội dung</label>
                <textarea asp-for="Content" rows="20" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <button type="submit" id="submitPostBtn" class="btn btn-submitPost">Đăng bài</button>
            <input asp-for="ForumId" type="hidden" />
        </form>
    </div>
}
else
{
    <h2>Ở trong tù thì không được đăng bài!!</h2>
}

@section Scripts {
    <script src="//@host/lib/tinymce/tinymce.min.js"></script> @*with enabled CDN tinymce is not able to find some files*@
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: ['advlist autolink lists link image charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks visualchars code fullscreen',
                'insertdatetime media nonbreaking save table contextmenu directionality',
                'emoticons template paste textcolor colorpicker textpattern imagetools'
            ],
            toolbar1: 'insertfile undo redo | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image |print preview media | forecolor backcolor emoticons|fontselect fontsizeselect styleselect'

        });
    </script>
    <partial name="_ValidationScriptsPartial" />
}

SimpleForum/Views/Post/Delete.cshtml
@model SimpleForum.Models.Post.DeletePostModel
@{ 
     ViewData["Title"] = "Xóa bài viết";
}
<div class="container body-content">
    @if (Model.IsActive)
    {
        <div class="row sectionHeader">
            <div class="sectionHeading">Bạn có chắc muốn xóa bài viết này hay không?</div>
            
        </div>
        <form asp-action="ConfirmDelete" asp-controller="Post">
            <input type="hidden" asp-for="PostId"/>
            <button id="deleteButton" class="btn btn-lg btn-danger">Xác nhận xóa</button>
            <button id="deleteButton" asp-controller="Post" asp-action="Index" asp-route-id="@Model.PostId" class="btn btn-lg btn-default" >Hủy</button>
        </form>
    }
    else
    {
        <div>
            <h2>Ở trong tù không được xóa bài!!</h2>
        </div>
    }
</div>

SimpleForum/Views/Post/Index.cshtml
@model SimpleForum.Models.Post.PostIndexModel
@using Microsoft.AspNetCore.Identity
@inject UserManager<SimpleForum.Data.Models.ApplicationUser> UserManager
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@{
    ViewData["Title"] = Model.Title;
    ViewData["Description"] = "Nội dung bài viết: " + Model.Title;
    var countCmt = 0;
}

<div class="container body-content">
    @if (!Model.IsReview || Model.AuthorID == UserManager.GetUserId(User) || User.IsInRole("Admin"))
    {
        <div class="row postHeader">
            <div class="postHeading" style="width:100%">
                <span class="postIndexTitle">
                    @Model.Title
                </span>
                <p style="float:right;" id="headingBtn"><a asp-controller="Forum" asp-action="Topic" asp-route-id="@Model.ForumId" class="btn btn-back">Quay lại @Model.ForumName</a></p>
            </div>
        </div>

        <div class="row" id="postIndexContent">
            <div class="col-md-3 postAuthorContainer">
                <div class="postAuthorImage" style="background-image: url(@Model.AuthorImageUrl);"></div>
                @if (Model.IsActive)
                {
                    <a asp-controller="Profile" asp-action="Detail" asp-route-id="@Model.AuthorID">@Model.AuthorName</a><br />
                }
                else
                {
                    <strike><a asp-controller="Profile" asp-action="Detail" asp-route-id="@Model.AuthorID">@Model.AuthorName</a></strike><br />
                }
                <span class="postData">@Model.Created</span><br />
                @if (Model.IsAuthorAdmin)
                {
                    <span style="color:red">Admin</span><br />
                }
                @if (Model.IsMod)
                {
                    <span style="color:hotpink">Mod</span><br />
                }
                @if (!Model.IsActive)
                {
                    <span style="color:black">Banned</span><br />
                }
            </div>
            <div class="col-md-9 postContentContainer">
                @{
                    await Html.RenderPartialAsync("_SocialSharing", Model.Title);
                }
                @if (Model.IsReview)
                {
                    <span style="color: red">Bài viết đang chờ BQT xét duyệt!</span><br />
                }
                @if (!Model.CloseOrOpen)
                {
                    <span style="color:red">Bài viết đã bị khóa bình luận.</span><br />
                }
                <div class="postContent">
                    @Html.Raw(Model.PostContent)
                </div>
            </div>
        </div>
        @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Mod") || UserManager.GetUserId(User) == Model.AuthorID))
        {
            var btnCloseOrOpenText = @Model.CloseOrOpen ? "Đóng bài viết" : "Mở bài viết";
            <div class="row">
                <span><a asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Slug" class="btn btn-danger">Xóa bài viết</a></span>
                <span><a asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Slug" class="btn btn-info">Sửa bài viết</a></span>
                @if (User.IsInRole("Admin") || User.IsInRole("Mod"))
                {
                    <span><a asp-controller="Post" asp-action="CloseOrOpen" asp-route-id="@Model.Slug" class="btn btn-dark">@btnCloseOrOpenText</a></span>
                    <span><a asp-controller="Post" asp-action="Move" asp-route-id="@Model.Slug" class="btn btn-secondary">Chuyển bài viết</a></span>
                }
                @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Mod")) && Model.IsReview == true)
                {
                    <span><a asp-controller="Post" asp-action="AcceptPost" asp-route-id="@Model.Slug" class="btn btn-info">Duyệt bài</a></span>
                }
            </div>
        }


        @*@if (Model.Replies.Any())
        {*@
            <div id="sectioncmt">
                @foreach (var r in ViewBag.OnePageOfReply)
                {
                    countCmt++;
                    <div class="row replyContent" id="@countCmt">
                        <div class="col-md-3 replyAuthorContainer">
                            <div class="postAuthorImage" style="background-image: url(@r.AuthorImageUrl)"></div>
                            @if (r.IsActive)
                            {
                                <a asp-controller="Profile" asp-action="Detail" asp-route-id="@r.AuthorId">@r.AuthorName</a><br />
                            }
                            else
                            {
                                <strike><a asp-controller="Profile" asp-action="Detail" asp-route-id="@r.AuthorId">@r.AuthorName</a></strike><br />
                            }
                            @if (r.IsAdmin)
                            {
                                <span style="color:red">Admin</span><br />
                            }
                            @if (r.IsMod)
                            {
                                <span style="color:hotpink">Mod</span><br />
                            }
                            @if (!r.IsActive)
                            {
                                <span style="color:black">Banned</span><br />
                            }
                            <span>@r.Date</span>
                        </div>
                        <div class="col-md-9 replyContentContainer">
                            <div class="postContent">
                                @Html.Raw(r.ReplyContent)
                            </div>
                            @if (User.Identity.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("Mod") || UserManager.GetUserId(User) == r.AuthorId))
                            {
                                <div class="row">
                                    <span><a asp-controller="Reply" asp-action="Delete" asp-route-id="@r.Id">Xóa trả lời | </a></span>
                                    <span><a asp-controller="Reply" asp-action="Edit" asp-route-id="@r.Id"> Sửa trả lời</a></span>
                                </div>
                            }
                        </div>
                    </div>
                }
            </div>
            @Html.PagedListPager((IPagedList)ViewBag.OnePageOfReply, pageNumber => Url.Action("Index", "Post", new { id = Model.Slug, pageNumber = pageNumber }))
        
        @*else
        {
            <div class="noPost">
                <h3>
                    Bài đăng này chưa có ai trả lời cả.<br />
                </h3>
            </div>
        }*@
    }
    else
    {
        <div class="noPost">
            <h3>
                Bạn không được xem bài viết này vì nó đang nằm trong danh sách cần kiểm duyệt.<br />
            </h3>
        </div>
    }
</div>

@if ((User.Identity.IsAuthenticated && Model.CloseOrOpen && !Model.IsReview) || User.IsInRole("Admin") || User.IsInRole("Mod"))
{
    <div class="row" style="margin-left:-3px; margin-bottom:15px;">
        <a asp-controller="Reply" asp-action="Create" asp-route-id="@Model.Slug" class="btn btn-newReply">Đăng trả lời</a>
    </div>
}
@section Scripts {
    <script src="~/js/lazy.js"></script>
    <script>
        var connection = new signalR.HubConnectionBuilder().withUrl("/notihub", { transport: signalR.HttpTransportType.WebSockets, skipNegotiation: true }).build();
        var duongDan;
        var cmtID;
        var trang;
        var currentUrl = location.pathname;
        connection.on("ReceiveNotify", function (slug, sectionID, page, data) {
            if (currentUrl.includes(slug)) {
                document.getElementById("notifyNewCmt").style.display = "block";
                $('#notifyNewCmt').delay(6000).fadeOut('slow');
                duongDan = slug;
                cmtID = sectionID;
                trang = page;
                var cmts = $('.replyContent').length;
                if (cmts < 10) {
                    $("#sectioncmt").append(data);
                }
            }
        });

        connection.start();

        function goToNewCmt() {
            window.location.assign('/Post/' + duongDan + '/' + trang + '#' + cmtID);
        };
    </script>
}

SimpleForum/Views/Post/Move.cshtml
@model SimpleForum.Models.Post.MovePostIndexModel
@{ 
     ViewData["Title"] = "Di chuyển bài viết";
}
<h1>Di chuyển bài viết</h1>

<div class="createPostSection">
    <form asp-action="MovePost" method="post">        
        <div class="form-group">
            <select class="form-control" asp-for="NewForumId">
                @foreach (var f in Model.Forums)
                {
                    <option value="@f.ID">@f.Title</option>
                }
            </select>
        </div>
        <button type="submit" class="btn btn-submitPost">Chuyển</button>
        <input asp-for="PostId" type="hidden" />
        <input asp-for="OldForumId" type="hidden"/>
    </form>
</div>