SimpleForum/Areas/Admin/Models/ModManager/ModManagerModel.cs
using SimpleForum.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SimpleForum.Areas.Admin.Models.ModManager
{
    public class ModManagerModel
    {
        public string Email { get; set; }
        public IEnumerable<ApplicationUser> User { get; set; }
    }
}

SimpleForum/Areas/Admin/Controllers/ModManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SimpleForum.Areas.Admin.Models.ModManager;
using SimpleForum.Data;
using SimpleForum.Data.Models;

namespace SimpleForum.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ModManagerController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IApplicationUser _userService;

        public ModManagerController(UserManager<ApplicationUser> userManager, IApplicationUser applicationUser)
        {
            _userManager = userManager;
            _userService = applicationUser;
        }

        public IActionResult Index()
        {
            var mods = _userService.GetAll()
                .Where(u =>  _userManager.GetRolesAsync(u).Result.Contains("Mod"))
                .OrderByDescending(u=>u.UserName);

            var model = new ModManagerModel
            {
                User = mods
            };
            
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddMod(string email)
        {
            var user = _userService.GetByEmail(email);

            if(user!=null)
                await _userManager.AddToRoleAsync(user, "Mod");

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveMod(string id)
        {
            var user = _userService.GetById(id);

            if (user != null)
                await _userManager.RemoveFromRoleAsync(user, "Mod");

            return RedirectToAction("Index");
        }
    }
}

SimpleForum/Areas/Admin/Views/ModManager/Index.cshtml
@model SimpleForum.Areas.Admin.Models.ModManager.ModManagerModel
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Quản lý các kiểm duyệt viên";
}



<div class="row" id="forumIndexContent">
    <h2>Quản lý kiểm duyệt viên</h2>
    <div >
        <form asp-area="Admin" asp-controller="ModManager" asp-action="AddMod" method="post" enctype="multipart/form-data" class="form-inline">           
            <div class="form-group mx-sm-3 mb-2">
                <label class="sr-only">Email</label>
                <input class="form-control" asp-for="Email" placeholder="Email">
            </div>
            <button type="submit" class="btn btn-primary mb-2">Thêm</button>
        </form>
    </div>

    @if (Model.User.Any())
    {
        <table class="table table-hover table-bordered" id="forumIndexTable">
            <tbody>
                @foreach (var u in Model.User)
                {
                    <tr>
                        <td>
                            <div class="forumLogo" style="background-image: url(@u.ProfileImageUrl.); background-size:100%"></div>
                            <div class="postData">
                                <div class="postTitle">
                                    <a asp-controller="Profile" asp-action="Detail" asp-route-id="@u.Id">@u.UserName</a>
                                </div>
                            </div>
                        </td>
                        <td>
                            <a class="btn btn-info" asp-area="Admin" asp-controller="ModManager" asp-action="RemoveMod" asp-route-id="@u.Id">Ngưng kiểm duyệt viên</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="noPosts">
            <h3>
                Hiện tại diễn đàn chưa có kiểm duyệt viên nào!!
            </h3>
        </div>

    }
</div>